canvas = document.getElementById("myCanvas");
color = "blue";
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = color ;
ctx.lineWidth = 5;
ctx.arc(200,200,40,0,2 * Math.PI);
ctx.stroke();
color = "black";
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = color ;
ctx.lineWidth = 5;
ctx.arc(290,200,40,0,2 * Math.PI);
ctx.stroke();
color = "red";
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = color ;
ctx.lineWidth = 5;
ctx.arc(380,200,40,0,2 * Math.PI);
ctx.stroke();
color = "yellow";
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = color ;
ctx.lineWidth = 5;
ctx.arc(240,250,40,0,2 * Math.PI);
ctx.stroke();
color = "green";
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = color ;
ctx.lineWidth = 5;
ctx.arc(340,250,40,0,2 * Math.PI);
ctx.stroke();
color = "grey";
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = color ;
ctx.lineWidth = 4;
ctx.arc(150,143,430,200);
ctx.stroke();